### ISSUE TITLE
Add missing crosshair to crosshair list

### ISSUE THREAD

**Issue by NachosChipeados** [R2Northstar/NorthstarDocs#39]
Theres an extra crosshair called ``ui/crosshair_turret``, found in ``mp_turretweapon_blaster.txt`` thats not included in the current crosshair list image found in the docs. Would be nice if it was included as well

https://github.com/user-attachments/assets/de42fc10-73de-414c-8524-ab176168043a

**Comment by GeckoEidechse** [comment]
I'm assuming you are referring to this list?

https://docs.northstar.tf/Modding/guides/keyvalue/crosshairmodding/#crosshair-index

**Comment by NachosChipeados** [comment]
Yup

**Comment by NachosChipeados** [comment]
Oh, and now that i look at it again, i noticed that its also missing ``ui/crosshair_sniper_amped``. I guess it should *probably* also be included for completeness sake, but with a small note that mentions its only visible when the weapon is amped

**Comment by EM4Volts** [comment]
> Oh, and now that i look at it again, i noticed that its also missing `ui/crosshair_sniper_amped`. I guess it should _probably_ also be included for completeness sake, but with a small note that mentions its only visible when the weapon is amped

tbh it misses.... ALOT of potential crosshairs but alot of them are either kinda something that already exists, or for very special use cases. such as the turret one uve shown, technically you can use the "recharging" thing that monarch has with his ability as a crosshair aswell

**Comment by GeckoEidechse** [comment]
As a first step it might make sense to switch the list from a screenshot of all the crosshairs to a table with a screenshot for each crosshair.
Then we can extend it pretty easily afterwards ^^
