### ISSUE TITLE
What happened to squidgyberries RSPNVPK?

### ISSUE THREAD

**Issue by begin-theadventure** [R2Northstar/NorthstarDocs#47]
https://r2northstar.readthedocs.io/en/latest/guides/tools/tools.html#rpsnvpk-s
https://github.com/squidgyberries/RSPNVPK Page not found

**Comment by GeckoEidechse** [comment]
Good question. Poking @squidgyberries

**Comment by GeckoEidechse** [comment]
Note sure where the difference between that version and https://github.com/Taskinoz/RSPNVPK is but we could link to the other version instead ^^
