### ISSUE TITLE
Weapon keyvalues page has a broken link

### ISSUE THREAD

**Issue by NachosChipeados** [R2Northstar/NorthstarDocs#56]
I imagine its probably meant to link to ``https://docs.northstar.tf/Modding/guides/keyvalue/``, but it doesn't.

![image](https://github.com/user-attachments/assets/ed365f65-2a4e-4874-8f78-54d5e4f2fe11)

![image](https://github.com/user-attachments/assets/353bd9d5-83b8-4069-804a-bb647d35c82f)

**Comment by GeckoEidechse** [comment]
Thanks for the heads-up <3
